stages:
  - build
  - deploy
  - destroy

variables:
  ANSIBLE_COMMAND_WARNINGS: "False"
  ANSIBLE_DEPRECATION_WARNINGS: "False"
  ANSIBLE_FORCE_COLOR: "True"
  ANSIBLE_HOST_KEY_CHECKING: "False"
  ANSIBLE_INVENTORY_ENABLED: "ini"
  ANSIBLE_ROLES_PATH: "/ansible"
  ANSIBLE_SSH_ARGS: "-o GSSAPIAuthentication=no -o ControlMaster=auto -o ControlPersist=600s -o UserKnownHostsFile=/dev/null"
  ANSIBLE_SSH_PIPELINING: "True"

image:
  name: registry.cn-hangzhou.aliyuncs.com/goldenimage/ansible:2.15.12

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - /ansible/
  policy: pull

before_script:
  - cp /etc/gitlab-runner/certs/gitlab.home.local.crt /usr/local/share/ca-certificates/ca.crt
  - update-ca-certificates

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - /ansible/
    policy: pull-push
  script:
    - ansible-galaxy install -r requirements.yml --force

deploy:
  stage: deploy
  script:
    - ansible-playbook -i hosts.ini deploy.yml -e ansible_password='{{ lookup("env", "ANSIBLE_PASSWORD") }}' -e ansible_sudo_pass='{{ lookup("env", "ANSIBLE_PASSWORD") }}'
  rules:
    - if: $CI_COMMIT_TITLE == "deploy"
      when: on_success