- name: ansible-role-OS-bootstrap
  src: git+https://gitea.home.local/suzhetao/ansible-role-OS-bootstrap.git
  version: origin/2.15-v0.1

- name: ansible-role-OS-beats
  src: git+https://gitea.home.local/suzhetao/ansible-role-OS-beats.git
  version: origin/2.15-v0.1

- name: ansible-role-vmware-guest
  src: git+https://gitea.home.local/suzhetao/ansible-role-vmware-guest.git
  version: origin/2.15-v0.1

- name: ansible-role-linux-nginx
  src: git+https://gitea.home.local/suzhetao/ansible-role-linux-nginx.git
  version: origin/2.15-v0.1

- name: ansible-role-linux-redis
  src: git+https://gitea.home.local/suzhetao/ansible-role-linux-redis.git
  version: origin/2.15-v0.1